Add CRUD operations to Books
wolox-training/mgl-java pull request #6
Opened 2020-03-02 17:39 UTC by marcegl91

## Summary
- Add CRUD operations to Books
## Trello Card
https://trello.com/c/v89X0OZR/18-crear-las-operaciones-crud-de-book

2020-03-02 23:39 UTC, leandrocostawolox requested changes
Great! I wrote some comments :)

2020-03-02 23:39 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/BookController.java
> + * BookController.java Controller for Books
Same as before, the class name is not necessary

2020-03-02 23:39 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/BookController.java
> +     * Find all books.
You can use here something like this:
```
    /**
     * Find all {@link Book}s.
```

So there will be a link to the Book class :) 
Same at the rest of the Javadocs

2020-03-04 14:46 UTC, zeminlu approved these changes
Looks good!

2020-03-04 15:24 UTC, merged